import 'package:flutter/material.dart';

class GridButton extends StatelessWidget {
  final String text;
  GridButton({this.text});
  Map<String, String> iconMap = {
    "અનાજ": '',
    "અન્ય": '',
    "કપાસ": 'cotton.png',
    "કરી લીફ": 'curryleaf.png',
    "કાસ્ટોર": 'Castor.png',
    "કુંવરપાઠુ": 'alovera.png',
    "કેરી": 'mango.png',
    "કેસર": 'Saffron.png',
    "કોકોનટ": 'Coconut.png',
    "ખેત": '',
    "ગ્યુંઅવા": 'Guava.png',
    "ઘઉં": '',
    "ચણા": 'Chickpeas.png',
    "ચીકુ": 'chikoo.png',
    "ચીલીઝ": 'Chillies.png',
    "જવ": 'Barley.png',
    "જીરું": 'Cumin.png',
    "જુવાર": 'Sorghum.png',
    "ટામેટા": 'Tomatoes.png',
    "ડુંગળી": 'Onion.png',
    "તમાકુ": 'Tobacco.png',
    "તરબૂચ": 'Watermelon.png',
    "તલ": 'Sesame.png',
    "તુલસી": 'Tulsi.png',
    "દાડમ": 'Pomegranate.png',
    "દૂધી": 'gourd.png',
    "ધાણા": 'Coriander.png',
    "નારંગી": 'Orange.png',
    "પપૈયા": 'Papaya.png',
    "પોટેટો": 'Potatoes.png',
    "બોવાઇન": 'Bovine.png',
    "ભીંડા": 'Ladies_finger.png',
    "મકાઇ": 'corn.png',
    "મકાઈ": 'corn.png',
    "મગફળી": 'Peanuts.png',
    "મેથી": 'Fenugreek.png',
    "મેરીગોલ્ડ": 'Marigold.png',
    "મેરીગોલ્ડમાં": 'Marigold.png',
    "રાઈ": 'mustard.png',
    "રીંગણ": 'Eggplant.png',
    "લવિંગ": 'Cloves.png',
    "લસણ": 'Garlic.png',
    "લીંબુ": 'Lemon.png',
    "લીલા ચણા": 'Chickpeas.png',
    "વરીયાળી": 'Aniseed.png',
    "શકરટેટી": 'sweetmelon.png',
    "સરસોં": 'mustard.png',
    "સીતાફળ": 'Custardapple.png',
    "સુવાદાણા બીજ": 'Dillseeds.png',
    'ડાંગર (ધન) (સામાન્ય)': '',
    'અરહર (તૂર / લાલ ગ્રામ) (સંપૂર્ણ)': 'Arhar.png',
    'ભીંડી (લેડીઝ ફિંગર)': 'Ladies_finger.png',
    'બ્રિંજલ': 'Eggplant.png',
    'કોબી': 'Cabbage.png',
    'ફૂલકોબી': 'Cauliflower.png',
    'ધાણા (પાંદડા)': 'Coriander.png',
    'આદુ (લીલો)': 'Ginger.png',
    'લીલો મરચું': 'Chillies.png',
    'ગવાર': '',
    'બાજરા (મોતીની બાજરી / કમ્બૂ)': '',
    'કાળો ગ્રામ (ઉર્દ દાળો) (સંપૂર્ણ)': 'Chickpeas.png',
    'જુવાર (જુવાર)': 'Sorghum.png',
    'કાબૂલી ચણા (ચણા-સફેદ)': 'Chickpeas.png',
    'રાજગીર': '',
    'તલ (તલ, ગિંજલી, તિલ)': 'Sesame.png',
    'બંગાળ ગ્રામ (ગ્રામ) (સંપૂર્ણ)': 'Chickpeas.png',
    'એરંડા બીજ': 'Castor.png',
    'કમિન બીજ (જીરા)': 'Cumin.png',
    'દુધી': 'gourd.png',
    'ગાજર': 'Carrot.png',
    'બટાટા': 'Potatoes.png',
    'ગવાર બીજ (ક્લસ્ટર બીજ)': 'mustard.png',
    'સરસવ': 'mustard.png',
    'મેથી (પાંદડા)': 'Fenugreek.png',
    'ડુંગળી લીલો': 'green_onion.png',
    // 'સુરત કઠોળ (પાપડી)': 'Surat Beans (Papadi)',
    'કેળા': 'Banana.png',
    'કોરિએન્ડર બીજ': 'Coriander.png',
    'સોયાબિન': 'Soyabean.png',
    'લીલો ગ્રામ (મૂંગ) (સંપૂર્ણ)': 'Chickpeas.png',
    'ગ્રાઉન્ડ બદામ બીજ': 'GroundNut.png',
    'મેથી સીડ્સ': 'Fenugreek.png',
    'ક્લસ્ટર કઠોળ': 'beans.png',
    'બીટનો કંદ': 'Beetroot.png',
    'કડવો લોટ': 'Bitter_gourd.png',
    'કાઉપિયા (વેજ)': '',
    'કુકુમ્બર (ખીરા)': 'Cucumbar.png',
    'ડ્રમસ્ટિક': 'Drumstick.png',
    'હાથી યમ (સુરન)': 'Yam.png',
    'ફ્રેન્ચ કઠોળ (ફ્રાસિયન)': 'beans.png',
    'ભારતીય કઠોળ (સીમ)': 'beans.png',
    // 'નાનો લોટ (કુંદરૂ)': '',
    'પીગન પેં (અરહર ફાલી)': 'Arhar.png',
    // 'પોઇંટેડ લોટ (પરવલ)': 'Pointed gourd (Parval)',
    'કોળુ': 'Pumpkin.png',
    // 'રીજ લોટ (ટોરી)': 'Ridge gourd(Tori)',
    'શક્કરિયા': 'Yam.png',
    'હળદર (કાચી)': 'Ginger.png',
    'યમ (રતલુ)': 'Yam.png',
    'કુલ્થી (ઘોડો ગ્રામ)': 'Chickpeas.png',
    // 'સોનફ': 'Soanf',
    'આમલા (નેલી કાઈ)': 'Amla.png',
    'કેળા - લીલોતરી': 'Banana.png',
    'પપૈયા (કાચો)': 'Papaya.png',
    'વટાણાની ભીની': 'Peas.png',
    'મૂળાની': 'Raddish.png',
    'પાલક': 'Spinach.png',
    // 'ટીંડા': 'Tinda',
    'કેપ્સિકમ': 'Capsicum.png',
    'ચિકૂઝ (સપોટા)': 'chikoo.png',
    'કોલાકેસીયા': 'Colacasia.png',
    'દ્રાક્ષ': 'Grapes.png',
    'જામફળ': 'Guava.png',
    'કિન્નુ': '',
    'મૌસામ્બી (મીઠી ચૂનો)': 'sweetmelon.png',
    'સ્ક્વોશ (ચપ્પલ કડુ)': 'Pumpkin.png',
    'એપલ': 'Apple.png',
    'મશરૂમ્સ': 'Mashrooms.png',
    'વટાણાની કodડ': 'Peas.png',
    'સલગમ': 'Turnip.png',
    // 'નૂલ ખોલ': 'Knool Khol',
    // 'ડાલડા': 'Dalda',
    // 'મહુઆ': 'Mahua',
    'સરસવનું તેલ': 'mustard.png',
    'ભાત': '',
    'ખાંડ': 'Sugar.png',
    'ઘઉં આટ્ટા': '',
    'સફેદ વટાણા': 'Peas.png',
    'કઠોળ': 'beans.png',
    'મરચું કેપ્સિકમ': 'Capsicum.png',
    // 'લીલો અવેર (ડબલ્યુ)': 'Green Avare (W)',
    // 'સીમેબદનેકાય': 'Seemebadnekai',
    // 'સાપની લોટ': 'Snake gourd',
    // 'સુવર્ણ ગડ્ડે': 'Suvarna Gadde',
    'મીઠો કોળુ': 'Pumpkin.png',
    // 'થોન્ડેકાય': 'Thondekai',
    // 'એમ્ફોફાલસ': 'Amphophalus',
    // 'એશગourર્ડ': 'Ashgourd',
    // 'અમરાન્થુસ': 'Amaranthus',
    'અનેનાસ': 'Pineapple.png',
    'ટેપિઓકા': 'Tapioca.png',
    'કાળા મરી': 'Black_pepper.png',
    'નાળિયેર તેલ': 'Coconut_Oil.png',
    'નાળિયેર': 'Coconut.png',
    'કેરી (કાચો-પાક)': 'mango.png',
    'મરી ungarbled': 'Black_pepper.png',
    'કોફી': 'Coffee.png',
    'રબર': 'Rubber.png',
    'દાળ (મસુર) (સંપૂર્ણ)': 'beans.png',
    'કરબુજા (કસ્તુરી તરબૂચ)': 'Musk_Melon.png',
    // 'ચૂનો': 'Lime',
    'આમલી ફળ': 'Tamarind.png',
    'લીલા વટાણા': 'Peas.png',
    'રાગી (ફિંગર બાજરી)': '',
    'ટંકશાળ (પુડીના)': 'Mint.png',
    'માછલી': 'Fish.png',
    // 'ઉંદર પૂંછડી મૂળા (મોગારી)': 'Rat Tail Radish (Mogari)',
    'ક્ષેત્ર વટાણા': 'Peas.png',
    'જવ (જૌ)': 'Barley.png',
    'કોપરા': 'Coconut.png',
    // 'ટીવી કમ્બૂ': 'T.V. Cumbu',
    // 'ગુર (ગોળ)': 'Gur(Jaggery)',
    'ડાંગર (ધન) (બાસમતી)': 'Basmati.png',
    'જેક ફળ': 'Jack_Fruit.png',
    'વટાણા (સુકા)': 'Peas.png'
  };
  @override
  Widget build(BuildContext context) {
    if (iconMap.containsKey(text)) {
      String iconFile = (iconMap[text] == '') ? 'grain.png' : iconMap[text];

      return Row(
        children: [
          Container(
            color: Colors.amber,
            height: 25,
            width: 25,
            child: Image(
              image: AssetImage('assets/icons/' + iconFile),
            ),
          ),
          SizedBox(width: 7),
          SizedBox(
            height: 50,
            width: 55,
            child: Align(
              alignment: Alignment.center,
              child: Text(
                text,
                style: TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.normal,
                    fontSize: 15),
              ),
            ),
          ),
        ],
      );
    }
    return Text(
      text,
      style: TextStyle(
          color: Colors.white, fontWeight: FontWeight.normal, fontSize: 15),
    );
  }
}
